
GET {{HOST_ADDRESS}}/weatherforecast/
Accept: application/json

### Post null fraction, which is allowed.

POST {{HOST_ADDRESS}}/weatherforecast/
Content-Type: application/json

{
    "fraction": null
}

### Post in fractional format, using dynamic separator based on selected environment.

POST {{HOST_ADDRESS}}/weatherforecast/
Content-Type: application/json

{
    "fraction": "1{{FRACTION_SEPARATOR}}5"
}

### Post in floating-point format.

POST {{HOST_ADDRESS}}/weatherforecast/
Content-Type: application/json

{
    "fraction": 0.2
}

### Model validation error: posted fraction outside allowed range.

POST {{HOST_ADDRESS}}/weatherforecast/
Content-Type: application/json

{
    "fraction": "-1{{FRACTION_SEPARATOR}}5"
}

### Model validation error: posted floating-point number outside allowed range.

POST {{HOST_ADDRESS}}/weatherforecast/
Content-Type: application/json

{
    "fraction": -0.2
}

### Model binding error: not a valid fraction.

POST {{HOST_ADDRESS}}/weatherforecast/
Content-Type: application/json

{
    "fraction": "?"
}

### Model binding error: not a valid floating-point number.

POST {{HOST_ADDRESS}}/weatherforecast/
Content-Type: application/json

{
    "fraction": 0;2
}

### Model binding error: Unexpected JSON.

POST {{HOST_ADDRESS}}/weatherforecast/
Content-Type: application/json

{
    "fraction": []
}
